backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# publish_mode: editorial_workflow
media_folder: "content/images" # Media files will be stored in the repo under images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    filter: {field: "layout", value: "Post"}
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "Post"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "youtube" # Used in routes, e.g., /admin/collections/blog
    label: "Youtube" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    filter: {field: "layout", value: "Youtube"}
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "Youtube"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "oglink" # Used in routes, e.g., /admin/collections/blog
    label: "OGLink" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    filter: {field: "layout", value: "OGLink"}
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "OGLink"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Remote Image", name: "remoteImage", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
